matrix:
  include:
    - os: osx
      compiler: clang
      language: cpp
      osx_image: xcode9.4
      env:
        - CMAKE_ARGS="-DRUSH_RENDER_API=MTL"
    - os: linux
      compiler: gcc
      language: cpp
      env:
        - CMAKE_ARGS="-DRUSH_RENDER_API=VK"
    - os: windows
      language: shell
      env:
        - CMAKE_ARGS="-A x64 -DRUSH_RENDER_API=VK"

notifications:
  email: false

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libxcb-xkb-dev libxcb-keysyms1-dev libx11-dev -y; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PATH=$PATH:/c/Program\ Files/CMake/bin; fi

script:
  - mkdir build
  - cd build
  - cmake ${CMAKE_ARGS} ..
  - cmake --build .
